import type { ReportMetadata } from "./types";

export const reportRegistry: readonly ReportMetadata[] = [
  {
    id: "tag-report",
    phase: "mvp",
    title: "Tag Report",
    sourceRepo: "StackExchange/so4t_tag_report",
    description: "Tag health, activity, response-time, SME, and coverage metrics.",
    supportedInstances: ["basic-business", "enterprise"],
    capabilities: ["live-api", "upload"],
    credentialRequirements: ["access-token", "api-key"],
    requiredDatasets: ["tags", "users", "questions", "articles", "tagSmes"],
  },
  {
    id: "api-user-report",
    phase: "mvp",
    title: "API User Report",
    sourceRepo: "StackExchange/so4t_api_user_report",
    description: "User contribution, reputation, inactivity, SME, and profile metrics.",
    supportedInstances: ["basic-business", "enterprise"],
    capabilities: ["live-api", "upload"],
    credentialRequirements: ["access-token", "api-key"],
    requiredDatasets: ["users", "questions", "articles", "tags", "reputationHistory", "communities"],
  },
  {
    id: "inactive-users",
    phase: "mvp",
    title: "Inactive Users",
    sourceRepo: "StackExchange/so4t_inactive_users",
    description: "Inactive user cohorts and content-risk segmentation.",
    supportedInstances: ["basic-business", "enterprise"],
    capabilities: ["live-api", "upload"],
    credentialRequirements: ["access-token", "api-key"],
    requiredDatasets: ["users"],
  },
  {
    id: "interactions",
    phase: "mvp",
    title: "Interactions",
    sourceRepo: "StackExchange/so4t_interactions_report",
    description: "Department-to-department interaction matrix and network view.",
    supportedInstances: ["basic-business", "enterprise"],
    capabilities: ["live-api", "upload"],
    credentialRequirements: ["access-token", "api-key"],
    requiredDatasets: ["users", "questions", "answers", "comments"],
  },
  {
    id: "community-members",
    phase: "mvp",
    title: "Community Members",
    sourceRepo: "StackExchange/so4t_community_members",
    description: "Community membership, SME, title, department, and email exports.",
    supportedInstances: ["basic-business", "enterprise"],
    capabilities: ["live-api", "upload"],
    credentialRequirements: ["access-token", "community-access"],
    requiredDatasets: ["communities", "users"],
  },
  {
    id: "data-export",
    phase: "mvp",
    title: "Data Export",
    sourceRepo: "StackExchange/so4t_data_export",
    description: "JSON export summaries for users, groups, tags, articles, questions, answers, and comments.",
    supportedInstances: ["basic-business", "enterprise"],
    capabilities: ["live-api", "upload"],
    credentialRequirements: ["access-token", "api-key"],
    requiredDatasets: ["users", "userGroups", "tags", "articles", "questions", "answers", "comments"],
  },
  {
    id: "webhook-report",
    phase: "later",
    title: "WebHook Report",
    sourceRepo: "StackExchange/so4t_WebHook_report",
    description: "Enterprise webhook scraping report.",
    supportedInstances: ["enterprise"],
    capabilities: [],
    credentialRequirements: ["enterprise-admin"],
    requiredDatasets: [],
    excludedReason: "Requires Selenium and admin-page scraping.",
  },
  {
    id: "search-log-report",
    phase: "later",
    title: "Search Log Report",
    sourceRepo: "StackExchange/so4t_search_log_report",
    description: "Enterprise search-log scraping report.",
    supportedInstances: ["enterprise"],
    capabilities: [],
    credentialRequirements: ["enterprise-admin"],
    requiredDatasets: [],
    excludedReason: "Requires Selenium login and admin/developer page scraping.",
  },
  {
    id: "api-import",
    phase: "later",
    title: "API Import",
    sourceRepo: "StackExchange/so4t_api_import",
    description: "Bulk import questions, answers, and articles.",
    supportedInstances: ["basic-business", "enterprise"],
    capabilities: [],
    credentialRequirements: ["access-token", "api-key"],
    requiredDatasets: [],
    excludedReason: "Write action reserved for guarded later phase.",
  },
  {
    id: "user-groups",
    phase: "later",
    title: "User Groups",
    sourceRepo: "StackExchange/so4t_user_groups",
    description: "Create groups and add users to groups.",
    supportedInstances: ["enterprise"],
    capabilities: [],
    credentialRequirements: ["access-token", "api-key"],
    requiredDatasets: [],
    excludedReason: "Write action reserved for guarded later phase.",
  },
  {
    id: "scim-user-activation",
    phase: "later",
    title: "SCIM User Activation",
    sourceRepo: "StackExchange/so4t_scim_user_activation",
    description: "Activate users through SCIM.",
    supportedInstances: ["basic-business", "enterprise"],
    capabilities: [],
    credentialRequirements: ["access-token"],
    requiredDatasets: [],
    excludedReason: "Privileged SCIM mutation reserved for later runner/backend phase.",
  },
  {
    id: "scim-user-deactivation",
    phase: "later",
    title: "SCIM User Deactivation",
    sourceRepo: "StackExchange/so4t_scim_user_deactivation",
    description: "Deactivate users through SCIM.",
    supportedInstances: ["basic-business", "enterprise"],
    capabilities: [],
    credentialRequirements: ["access-token"],
    requiredDatasets: [],
    excludedReason: "Privileged SCIM mutation reserved for later runner/backend phase.",
  },
  {
    id: "scim-user-deletion",
    phase: "later",
    title: "SCIM User Deletion",
    sourceRepo: "StackExchange/so4t_scim_user_deletion",
    description: "Delete users through SCIM.",
    supportedInstances: ["basic-business", "enterprise"],
    capabilities: [],
    credentialRequirements: ["access-token"],
    requiredDatasets: [],
    excludedReason: "Destructive SCIM mutation reserved for later runner/backend phase.",
  },
];

export function getExecutableReports(): readonly ReportMetadata[] {
  return reportRegistry.filter((report) => report.phase === "mvp");
}
